# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from mytype import users_types_pb2 as users__types__pb2


class UsersStub(object):
  """定义服务接口
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/Users/CreateUser',
        request_serializer=users__types__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=users__types__pb2.CreateUserResult.FromString,
        )
    self.GetUsers = channel.unary_stream(
        '/Users/GetUsers',
        request_serializer=users__types__pb2.GetUsersRequest.SerializeToString,
        response_deserializer=users__types__pb2.GetUsersResult.FromString,
        )


class UsersServicer(object):
  """定义服务接口
  """

  def CreateUser(self, request, context):
    """接口名       接口接受的消息类型              接口返回的消息类型
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    """将返回指定为流
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=users__types__pb2.CreateUserRequest.FromString,
          response_serializer=users__types__pb2.CreateUserResult.SerializeToString,
      ),
      'GetUsers': grpc.unary_stream_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=users__types__pb2.GetUsersRequest.FromString,
          response_serializer=users__types__pb2.GetUsersResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
