# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0finterface.proto\x1a\x0btypes.proto2,\n\x04Test\x12$\n\x08send_msg\x12\x0b.types.msg1\x1a\x0b.types.msg1b\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=32,
  serialized_end=76,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_msg',
    full_name='Test.send_msg',
    index=0,
    containing_service=None,
    input_type=types__pb2._MSG1,
    output_type=types__pb2._MSG1,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
